### ISSUE TITLE
getPath return partial data and serie of NaN

### ISSUE THREAD

**Issue by edouard-lopez** [shrhdk/text-to-svg#22]
**related:** #23  

### Env

* text-to-svg: `^3.1.0`,
* font: https://github.com/googlei18n/noto-cjk/blob/master/NotoSansTC-Regular.otf

### Code

```
import TextToSVG from "text-to-svg";

const textToSVG = TextToSVG.loadSync(
  "./resources/fonts/NotoSansTC-Regular.otf"
);
const svg = textToSVG.getSVG("yǐn");
console.log(svg);
```

Output:

```
$ node --require babel-core/register ./debug.js 
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="101.30400000000002" height="106.56000000000002"><path d="M0-7.13L4.61-7.13L4.61-13.68C8.57 3.67 4.82NaNNaNNaNLNaNNaNLNaNNaNLNaNNaN"/></svg>
```

### Error

Above is a short snippet that reproduce the but, in the context of my app I got more info:

```
yǐn <path fill="black" stroke="black" id="annotation" d="M39.24 15.98L40.26 15.98L40.26 14.52C41.14 18.38 40.31NaNNaNNaNLNaNNaNLNaNNaNLNaNNaN"/>
already exists
Error: Got an error parsing the glyph "㐆": Unexpected character "N" at index 54..
    at SAXStream.<anonymous> (/data/projects/hanzi-pinyin-font/node_modules/svgicons2svgfont/src/index.js:245:29)
    at emitOne (events.js:96:13)
    at SAXStream.emit (events.js:188:7)
    at Object.me._parser.(anonymous function) [as onopentag] (/data/projects/hanzi-pinyin-font/node_modules/sax/lib/sax.js:258:17)
    at emit (/data/projects/hanzi-pinyin-font/node_modules/sax/lib/sax.js:640:35)
    at emitNode (/data/projects/hanzi-pinyin-font/node_modules/sax/lib/sax.js:645:5)
    at openTag (/data/projects/hanzi-pinyin-font/node_modules/sax/lib/sax.js:841:5)
    at Object.write (/data/projects/hanzi-pinyin-font/node_modules/sax/lib/sax.js:1305:13)
    at SAXStream.write (/data/projects/hanzi-pinyin-font/node_modules/sax/lib/sax.js:239:18)
    at Readable.ondata (_stream_readable.js:555:20)
(node:4788) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'svg' of undefined
Done in 2.25s.
```

**Comment by edouard-lopez** [comment]
I tried with another content without problem:

     wǔ <path fill="black" stroke="black" id="annotation" d="M41.51 17.56L43.22 17.56L44.44 12.90C44.66 12.07 44.84 11.26 45.03 10.38L45.11 10.38C45.32 11.26 45.48 12.06 45.70 12.87L46.97 17.56L48.73 17.56L51.06 8.87L49.69 8.87L48.41 13.90C48.22 14.73 48.06 15.51 47.86 16.33L47.80 16.33C47.59 15.51 47.40 14.73 47.19 13.90L45.83 8.87L44.41 8.87L43.06 13.90C42.84 14.71 42.66 15.51 42.47 16.33L42.39 16.33C42.23 15.51 42.06 14.73 41.88 13.90L40.58 8.87L39.10 8.87ZL41.34 23.72M41.48 13.24L42.94 13.24"/>

**Comment by edouard-lopez** [comment]
Using `DroidSansFallbackFull` fixed my problem.
